### ISSUE TITLE
bug 报告 压缩jpg时遇到webp文件后报错跳出

### ISSUE THREAD

**Issue by appotry** [xinlin-z/smally#29]
```
# python3 /app/tools/smally/smally.py -p /app/userConfig/cloudimg-min/data/2021/09 -r -k --jpegtran --jpg
Traceback (most recent call last):
  File "/app/tools/smally/smally.py", line 193, in <module>
    main()
  File "/app/tools/smally/smally.py", line 181, in main
    pJpegtran(ptype, interval, args.recursive, args.timewindow,
  File "/app/tools/smally/classes.py", line 216, in __init__
    it.start(paths)
  File "/app/tools/smally/classes.py", line 123, in start
    for path in top: it.go(path)
  File "/app/tools/smally/classes.py", line 149, in go
    it.do(pathname)
  File "/app/tools/smally/classes.py", line 247, in do
    raise ChildProcessError('%s: error while jpegtran baseline '
ChildProcessError: [smally]: error while jpegtran baseline compression
Not a JPEG file: starts with 0x89 0x50
```

**Comment by xinlin-z** [comment]
收到。
这个版本的smally按照文件后缀来区分type，应该是webp图片使用了jpg后缀，但程序确实不应该崩溃，应该继续。

你看看通过修复文件后缀，是否可以临时解决问题？

我在酝酿smally的全面更新，smally是我的第一次开源尝试，项目实现现在看来，复杂了，提供的功能有点混乱，我想简化。因此，如果修复后缀能够work around，我就暂时不修改代码。等后面有空了，全面更新。

**Comment by appotry** [comment]
对我笔记里面的图片压缩的时候，发现一些图片后缀乱来，有一批webp命名为jpg，一批png，被以jpg后缀命名

然后就出错跳出来了。


换个方式，硬链接到新目录，删除所有其它后缀的图片。然后 -p 运行，出错跳出

再换个方式 find xargs 结合smally -f 来运行，还是出错跳出来。

再想办法，结合shell 命令 file 判断文件类型，还在搞 


通过后缀来区分文件类型是不靠谱的，有些人乱命名，你没法控制别人怎么整。 用file 判断类型再传入后端，才靠谱

**Comment by appotry** [comment]
改文件名比较麻烦，笔记软件不支持全局替换文件名，改了名字运行应该没问题，但是笔记就引用不了了，还要再改回去

**Comment by xinlin-z** [comment]
master branch is updated, 可以试一下。

**Comment by xinlin-z** [comment]
> 对我笔记里面的图片压缩的时候，发现一些图片后缀乱来，有一批webp命名为jpg，一批png，被以jpg后缀命名
> 
> 然后就出错跳出来了。
> 
> 换个方式，硬链接到新目录，删除所有其它后缀的图片。然后 -p 运行，出错跳出
> 
> 再换个方式 find xargs 结合smally -f 来运行，还是出错跳出来。
> 
> 再想办法，结合shell 命令 file 判断文件类型，还在搞
> 
> 通过后缀来区分文件类型是不靠谱的，有些人乱命名，你没法控制别人怎么整。 用file 判断类型再传入后端，才靠谱

Good Idea

**Comment by appotry** [comment]
初步测试，新版遇到错误后缀没有跳出

**Comment by xinlin-z** [comment]
> 初步测试，新版遇到错误后缀没有跳出

多谢使用，请关注后续的新版本，我计划在保留核心功能的原则下，简化代码和使用。需要点时间，最近太忙了。。。:(

**Comment by xinlin-z** [comment]
> 对我笔记里面的图片压缩的时候，发现一些图片后缀乱来，有一批webp命名为jpg，一批png，被以jpg后缀命名
> 
> 然后就出错跳出来了。
> 
> 换个方式，硬链接到新目录，删除所有其它后缀的图片。然后 -p 运行，出错跳出
> 
> 再换个方式 find xargs 结合smally -f 来运行，还是出错跳出来。
> 
> 再想办法，结合shell 命令 file 判断文件类型，还在搞
> 
> 通过后缀来区分文件类型是不靠谱的，有些人乱命名，你没法控制别人怎么整。 用file 判断类型再传入后端，才靠谱

欢迎试试新版本，采用了你的主意，用file来判断文件类型，做了大量的简化：） @appotry

**Comment by appotry** [comment]
新版使用更方便了 赞 个人博客给你做推荐😀

xinlin-z ***@***.***> 于2022年6月1日周三 18:04写道：
